### ISSUE TITLE
Make sure notebook canvas renderings still work with the instrumentation enabled

### ISSUE THREAD

**Issue by motin** [mozilla/openwpm-webext-instrumentation#16] opened 2018-11-02 23:05 UTC
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
We noticed that some canvas elements in exported notebooks no longer load when the instrumentation is enabled. This may indicate a bug that also leads to canvas-related breakage elsewhere.

**Comment by motin** [comment] 2018-11-02 23:12
This stack trace from the browser console after terminating the long-running script hints that it stalls in `getStackTrace`.

```
Error: Script terminated by timeout at:
getStackTrace@https://metrics.mozilla.com/~sbird/overscripted-clustering/clusters/working_assumption_and_refinement/precision%20bundling%20-%20part%201.html:162:21
getOriginatingScriptContext@https://metrics.mozilla.com/~sbird/overscripted-clustering/clusters/working_assumption_and_refinement/precision%20bundling%20-%20part%201.html:175:23
instrumentFunction/<@https://metrics.mozilla.com/~sbird/overscripted-clustering/clusters/working_assumption_and_refinement/precision%20bundling%20-%20part%201.html:454:33
o</i.fixup_ctx/i.measureText@https://cdn.pydata.org/bokeh/release/bokeh-1.0.0.min.js:31:72193
instrumentFunction/<@https://metrics.mozilla.com/~sbird/overscripted-clustering/clusters/working_assumption_and_refinement/precision%20bundling%20-%20part%201.html:456:20
o</i.fixup_ctx/i.measureText@https://cdn.pydata.org/bokeh/release/bokeh-1.0.0.min.js:31:72193
instrumentFunction/<@https://metrics.mozilla.com/~sbird/overscripted-clustering/clusters
```

**Comment by englehardt** [comment] 2018-11-06 18:28
This appears to be related to the bokeh script mucking with the `measureText` prototype. The `fixup_ctx` function includes the following:

```javascript
(i = t).measureText && null == i.html5MeasureText && (i.html5MeasureText = i.measureText, i.measureText = function (t) {
          var e = i.html5MeasureText(t);
          return e.ascent = 1.6 * i.html5MeasureText('m').width,
          e
        }),
```

**Comment by englehardt** [comment] 2018-11-07 00:08
I spent a bit more time debugging this, and I believe the root cause is an unfortunate side effect of the way we've written our current instrumentation. Here's my current understanding.

When their code assigns a new method to `measureText` on an instance of `CanvasRenderingContext2D`, we write that method out to the prototype object for `CanvasRenderingContext2D`. Since they call the original method in their overwritten method, we end up with nested `instrumentFunction` calls. Each call to `fixup_ctx` makes this worse, adding another layer of `instrumentFunction` to `measureText`.

A simple fix for this is to add the `preventSets: true` option to each `instrumentObject` call. This prevents sites from overwriting any built-in, instrumented method by silently dropping any overwrite attempts. The problem with doing this is that we'll break any monkey patching done by sites, possibly breaking the experience for users. @motin does this sound acceptable?

Note that there are still performance issues even when this fix is applied, but they aren't so bad that the page stalls.

**Comment by englehardt** [comment] 2018-11-07 00:18
Also note that it might be possible to fix this properly, but I suspect it will be a time consuming fix. I've found messing with getters and setters on prototype objects to not be the most straightforward task, but perhaps you have more experience here than I do :)

**Comment by motin** [comment] 2018-11-07 01:03
Greatly investigated!
Is this unique to our instrumentation or do we know of other instrumentation that uses the same approach and thus also should break sites that monkey-patches prototypes?
Preventing monkey-patching would likely break more libraries and experiences than we would like
What if we cap the amount of `instrumentFunction` calls that our instrumentation is allowed to do, so that an infinite loop does not occur?

**Comment by englehardt** [comment] 2018-11-07 01:51
> Is this unique to our instrumentation or do we know of other instrumentation that uses the same approach and thus also should break sites that monkey-patches prototypes?

Not that I know of. Privacy Badger is probably the closest thing I know of. See:https://github.com/EFForg/privacybadger/blob/master/src/js/contentscripts/fingerprinting.js.

> What if we cap the amount of instrumentFunction calls that our instrumentation is allowed to do, so that an infinite loop does not occur?

Doing so globally wouldn't fix this problem unfortunately. As an alternative, we could drop overwrites on built-in methods after some small cutoff. Let's say something between 1 and 5 sets. If a script attempts to overwrite a built-in method more than N times, all attempts >= N will be ignored. That should prevent the issue while allowing most monkey patching to work?

Another (dirty) alternative could be to compare the new method to previous one at the time of the set. If the new method is the same (once stringified) as the one that's already set, we can skip the set.

For future references I think this stems from assumptions we made about what descriptors are available to us for properties of prototype objects. We should carefully check the availability of [`originalGetter`, originalSetter`, and `originalValue`](https://github.com/mozilla/openwpm-webext-instrumentation/blob/dcd28b3c1f264efcaa7eb523c2239ac4b1f1b2cd/src/content/javascript-instrument-page-scope.ts#L570-L573) for both accessor and data properties -- both for calls to `instrumentObject` on prototypes (like `CanvasRenderContext2D.prototype`) and on non-prototypes (like `document.cookie`). I suspect there's a bug in the way we handle accessor properties of prototypes that's leading to this problem. Thankfully this should only cause issues when a page overwrites built-in, instrumented methods multiple times during a visit (which I suspect is quite rare).

We should also investigate why the bokeh script is able to call the code above multiple times without leading to the layering we experience when the instrumentation is active.

**Comment by englehardt** [comment] 2018-11-09 17:09
@motin do you have any concerns with either of the approaches above?

**Comment by motin** [comment] 2018-11-09 18:09
No concerns at this point. Good reasoning! Implementing the 1-5 cutoff to drop overwrites seems like the best short-term solution, especially if it results in a message/event informing about the fact that the cutoff was reached. This allows us to avoid breaking things and understand how prevalent this issue is. 

If you can file a PR for this it would be superb!

The long-term solution of writing the instrumentation differently can be considered a separate issue.

**Comment by englehardt** [comment] 2018-11-14 06:39
#19 will fix this. This bug is actually much more impactful than just performance. We were saving updates to data properties on the prototype object, which means that a `set` on any object which uses that prototype impact all future `get`s for all objects. The rate limiting approaches above wouldn't fix the fact that changes which should have been applied locally were applied globally. #19 fixes the root cause.

Note that it's not the ideal solution since we can't instrument future calls to overwritten methods / objects. We could achieve that by using:

```javascript
Object.defineProperty(this, propertyName, {
    get: instrumentedGetter,
    set: instrumentedSetter,
});
```

but this will require a bit of refactoring as we don't want to completely replicate all of the current getter/setter instrumentation. Once we merge we should file a follow-up issue to address this.

**Closed** 2018-11-14 13:00 UTC
Labels: help wanted
